### ISSUE TITLE
Subaddress section should describe Janus attack

### ISSUE THREAD

**Issue by tusing** [monerodocs/md#21]
The subaddress section implies that subaddresses are enough to maintain separate identities, but in the case of two colluding entities with disparate subaddresses, subaddresses are not sufficient.

The documentation should add a disclaimer that until Janus is mitigated, maintaining entirely separate wallets per desired identity is recommended for utmost privacy.

see:
- https://web.getmonero.org/2019/10/18/subaddress-janus.html
- https://github.com/monero-project/research-lab/issues/62

**Comment by qertoip** [comment]
Thank you for drawing my attention to this issue. I will fix the docs.

**Comment by qertoip** [comment]
Fix deployed.
