### ISSUE TITLE
Possible typo in monerod command reference.

### ISSUE THREAD

**Issue by donkey-donkey** [monerodocs/md#24]
In the Node RPC API section for this entry
```
--rpc-restricted-bind-ip | IP to listen on with the limited version of API. The limited API can be made public to create an Open Node.
-- | --
--rpc-restricted-bind-port | TCP port to listen on with the limited version of API. To be used in combination with `--rpc-restricted-bind-port.
```
the rpc-restricted-bind-port says it should be used in combination with rpc-restriced-bind-port. i think it should maybe say used in combination with rpc-restricted-bind-ip

thanks.

**Comment by qertoip** [comment]
Of course, thanks! Fixed.
