### ISSUE TITLE
Docs are Terrible 

### ISSUE THREAD

**Issue by Librechain** [monerodocs/md#25]
No other way to put it. 

This is the most incomplete documentation I've come across in quite some time (and that's saying a lot considering we're in the crypto space). 

There are multiple pages that are simply incomplete, incorrect or both. And that actually hurts a lot more than it helps. 

If I had more personal free time and thought that the "developers" of this project were honest people that had intentions on protecting the project from warlording, then I would definitely be about it. But, unfortunately, I'm not. And I dislike the fact that Monero is built to benefit the pockets of a few (like the core developers ; i.e., 'Spagni').

Change is coming in the near future. The community has mandated it.

**Comment by qertoip** [comment]
MoneroDocs.org is **unofficial** and indeed incomplete documentation created by a single person in my spare time. I am sorry quality disappointed you.

MoneroDocs is **NOT** ran or endorsed by the core developers, so please do not blame them for any issues of my website. Whatever is incorrect or missing, it is on me personally.

Finally, I have Monro core devs in the highest regard and decisively do not share your sentiment.

Of course, pull requests are welcome.

**Comment by Librechain** [comment]
> MoneroDocs.org is **unofficial** and indeed incomplete documentation created by a single person in my spare time. I am sorry quality disappointed you.
> 
> MoneroDocs is **NOT** ran or endorsed by the core developers, so please do not blame them for any issues of my website. Whatever is incorrect or missing, it is on me personally.
> 
> Finally, I have Monro core devs in the highest regard and decisively do not share your sentiment.
> 
> Of course, pull requests are welcome.

I'd be more than happy to help amend the documentation here for Monero. 

Additionally, I have a recommendation for another site / format that you should use for displaying the Monero documentation. 

I apologize if you perceived my original created issue as antagonistic to what you're trying to do. Let me know how I can help you out. You have a good point in saying that the documentation is unofficial and self-supported, so I'm more than happy to contribute additional items that I feel would bring it up to par.

**Comment by qertoip** [comment]
> I'd be more than happy to help amend the documentation here for Monero.

Great!

> Additionally, I have a recommendation for another site / format that you should use for displaying the Monero documentation.

Always happy to hear. Though I do like mkdocs very much and I picked it after reviewing a couple of popular documentation formats.
