### ISSUE TITLE
Request for Info on Contributing 

### ISSUE THREAD

**Issue by Librechain** [monerodocs/md#26]
In lieu of my last pulled issue, I concur with the maintainer of this repo that it would be more constructive to make a pull request rather than point out what I perceive as deficits in the current version. 

There are a few places where I'm sure that I can contribute. Let me know what the process for doing that would be (i.e., just a simple pull request, notes on the amendments + reason added[?]), etc.

**Comment by qertoip** [comment]
Just a simple pull request would be great. Thank you!
