### ISSUE TITLE
can you simply introduce peer network protocol in monero

### ISSUE THREAD

**Issue by mingjiedengofficial** [monerodocs/md#33]
I am doing some research about monero, but i don't find any detained introdution about peer network protocol in monero. So can you introduce peer network protocol of monero in this github project. Thank you!

**Comment by qertoip** [comment]
I fully agree the p2p protocol should be documented. I would very much welcome a PR. Even just an introduction with further references to the code base would be nice.

**Comment by qertoip** [comment]
Closing the issue as it is not actionable for me at the moment.
