### ISSUE TITLE
Subaddress generation algorithm description is outdated

### ISSUE THREAD

**Issue by emesik** [monerodocs/md#4]
I was investigating that recently to implement subaddr generation. The algorithm described on monerodocs.org is outdated, probably originating from first proposal of such feature.

[This answer on stackexchange](https://monero.stackexchange.com/a/10676/3616) describes the right version. And there's a nice JS implementation mentioned at the end.

**Comment by qertoip** [comment]
Thanks a lot! Will have a look on this.

**Comment by emesik** [comment]
Also, [my implementation](https://github.com/emesik/monero-python/blob/c999f68cf1bc76091258abafa587f21075d2be99/monero/wallet.py#L195) might be even easier to understand. The JS version used some complex types internally, while mine operates on integers (being ridiculously slow BTW).

**Comment by qertoip** [comment]
This is now fixed thanks to your clean Python implementation and the referenced stack exchange answer by knaccc. Thanks so much!
