### ISSUE TITLE
Appears both testnet faucets are dead links.

### ISSUE THREAD

**Issue by felixfarquharson** [monerodocs/md#42]

**Comment by qertoip** [comment]
Do you by any chance came across good alternatives? I would welcome stagenet and testnet faucet suggestions.

**Comment by boldsuck** [comment]
You can mine 100th stagenet & testnet XMR yourself in a few minutes ;-)
`-$ monerod --start-mining <YOUR XMR STAGENET ADDRESS> --mining-threads <NUMBER OF THREADS>`

Or add in your bitmonero.conf:
```
start-mining=<YOUR XMR STAGENET ADDRESS>
mining-threads=<NUMBER OF THREADS>

```
To completeness [monerod daemon RPC call #start_mining](https://web.getmonero.org/resources/developer-guides/daemon-rpc.html#start_mining)

_Enjoy becoming a stagenet millionaire._

**Comment by qertoip** [comment]
Now fixed.
