### ISSUE TITLE
Invalid peer addresses in example config

### ISSUE THREAD

**Issue by semyon2105** [monerodocs/md#44]
In the [config example](https://monerodocs.org/running-node/open-node-tor-onion/#etcmoneroconf), most of the hosts specified inside "add-peer" and "add-priority-peer" options have RPC ports instead of P2P ports. Also, a comment there points to a few websites where you could get a list of Monero nodes, but those websites only list RPC addresses.

**Comment by qertoip** [comment]
You are right, [facepalm].

It's now fixed with onion peer nodes from https://www.ditatompel.com/monero/node-peers
