### ISSUE TITLE
[Proposal] Transfer this repository to the Monero Ecosystem project

### ISSUE THREAD

**Issue by erciccione** [monerodocs/md#8]
i always found monerodocs a very useful source of information and it's a waste that not many in the Monero community are aware of it's existence,

Would you consider transferring the repo to the [Monero Ecosystem project](https://github.com/monero-ecosystem) and maintain it from there.

It would have more visibility in the Ecosystem and i would personally be happy to contribute to moerodocs when i can. Please see [the readme](https://github.com/monero-ecosystem/meta/blob/master/readme.md) for info about the Ecosystem and the governance process we adopted

**Comment by qertoip** [comment]
Thanks a lot for your kind words and proposal!

I greatly appreciate your work on the Ecosystem but I am not sure about the centralized control over repositories under any organization. I think I prefer the "curated awesome list" approach that decouples organization from control.

So, for the time being I will stay within my org/repo, but I am also open to reconsider this in the future.

Thanks!

**Comment by erciccione** [comment]
Thank you for the answer :)
